### ISSUE TITLE
Error 630 on Expert Blocks

### ISSUE THREAD

**Issue by tommyahugo** [cyberkitsune/PSO2Proxy#196]
The update on October 5th add new blocks call Expert Block from B14 to B21. Everytime I try to access to these blocks I got error 630. In PSO world and facebook group it seem those who use proxy also have the same problem. They also specified that it is this proxy because Seiryl's proxy work fine.

**Comment by alama** [comment]
Already fixed in https://github.com/cyberkitsune/PSO2Proxy/pull/195

**Comment by tommyahugo** [comment]
Sorry but I still have the issue. Do i have to do any extra step?

**Comment by acffordyce973** [comment]
The public proxy has yet to be restarted to update to the fixed version (it's hard to find a time to not inconvenience so many users) hence why the issue is still occurring here. Smaller proxies will obviously have an easier time restarting and can update to the latest version quicker (hence why Seiryl is working).

**Comment by tommyahugo** [comment]
Ah, ok, then I guess the issue is solved now.
